export const SET_WEATHER_START = "SET_WEATHER_START";
export const SET_WEATHER_SUCCESS = "SET_WEATHER_SUCCESS";
export const SET_FORECAST_LENGTH = "SET_FORECAST_LENGTH";
export const SET_WEATHER_ERROR = "SET_WEATHER_ERROR";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_ERROR = "SET_IS_ERROR";
